### ISSUE TITLE
请问作者有没有遇到过高并发请求的问题？

### ISSUE THREAD

**Issue by alazycoder** [WenmuZhou/flask_pytorch#1]
您好。假如有很多个client同时请求您的接口，您的程序会load一次model还是load多次呢？显存会爆炸吗？这个问题困扰了我许久，期待您的解答。

**Comment by WenmuZhou** [comment]
model只在server启动的时候load一下，后面都只执行前向

**Comment by alazycoder** [comment]
懂了，谢谢您的回复。


| |
lazysheep111
|
|
lazysheep111@163.com
|
签名由网易邮箱大师定制
在2019年8月12日 08:58，zhoujun<notifications@github.com> 写道：

model只在server启动的时候load一下，后面都只执行前向
